### ISSUE TITLE
Take too long for run

### ISSUE THREAD

**Issue by andifoza** [Hax4us/haxRat#1]
![Screenshot_20200629-154902_Termux](https://user-images.githubusercontent.com/65265922/85993199-245cc200-ba20-11ea-9789-3031346d6529.jpg)

I dont know it normal or not
But it Take too long time for run?

**Comment by Hax4us** [comment]
Please watch practical videos of haxRat for more information

How to install ? https://youtu.be/OXHgTBYtneU
Setup first time https://youtu.be/VvcE5zEjiK0
