### ISSUE TITLE
Apk build not work

### ISSUE THREAD

**Issue by tonystarksn** [Hax4us/haxRat#12]
![Screenshot_20200814_025502](https://user-images.githubusercontent.com/69654658/90195148-5f576100-dde6-11ea-9802-f134e3fa79c0.jpg)

![Screenshot_20200814_002838](https://user-images.githubusercontent.com/69654658/90194998-1d2e1f80-dde6-11ea-8f1b-5eb8bd282dba.jpg)

**Comment by tonystarksn** [comment]
Fixed

**Comment by emirbyte** [comment]
@tonystarksn how did you fix it?
