### ISSUE TITLE
Build Command Failed - Command failed: java -jar "/home/azamet/Belgeler/cehennem/haxRat/server/app/factory/apktool.jar" b "/home/azamet/Belgeler/cehennem/haxRat/server/app/factory/decompiled" -o "/home/azamet/Belgeler/cehennem/haxRat/server/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true brut.androlib.AndrolibException: java.io.FileNotFoundException: /home/azamet/.local/share/apktool/framework/1.apk (Böyle bir dosya ya da dizin yok) 

### ISSUE THREAD

**Issue by azamet90** [Hax4us/haxRat#17]
not working

**Comment by Hax4us** [comment]
i am busy nowdays i will come back ASAP

**Comment by azamet90** [comment]
> i am busy nowdays i will come back ASAP

Build Command Failed - Command failed: java -jar "/home/xxx/Belgeler/cehennem/haxRat/server/app/factory/apktool.jar" b "/home/xxx/Belgeler/cehennem/haxRat/server/app/factory/decompiled" -o "/home/azamet/Belgeler/cehennem/haxRat/server/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true brut.androlib.AndrolibException: java.io.FileNotFoundException: /home/xxx/.local/share/apktool/framework/1.apk (no such file directory) 


another error

**Comment by azamet90** [comment]
okay im very sorry not the tool i was garbage :D fixed after using sudo and thanks for making this tool only gps is not working but its still cool
