### ISSUE TITLE
Apkmod -r problems

### ISSUE THREAD

**Issue by FohrtuniaFX** [Hax4us/haxRat#22]
![Screenshot_20201208-194801_Termux](https://user-images.githubusercontent.com/65709814/101527484-5b9bab80-398e-11eb-8c0f-8cedf7cbb3bb.jpg)
I dont know why please help me and teach me what to do

**Comment by jatinyadav008** [comment]
I am also facing the same problem please help me if you get solution

**Comment by NeguinDev** [comment]
https://github.com/Hax4us/Apkmod

**Comment by Gregnald** [comment]
What is this ?
![Screenshot_2021-03-19-19-42-45-209_com.termux.jpg](https://user-images.githubusercontent.com/79373546/111793891-b7f65b80-88eb-11eb-8cd1-964fa66eaec0.jpg)

**Comment by Hax4us** [comment]
@avistnm some apps can't be bind

**Comment by Gregnald** [comment]
Okay
