### ISSUE TITLE
Apkmod not found

### ISSUE THREAD

**Issue by sgvchud** [Hax4us/haxRat#3]
ERROR Build Failed - Build Command Failed - Command failed: apkmod -r "/data/data/com.termux/files/usr/share/haxrat/server/app/factory/decompiled" -o "/data/data/com.termux/files/home/haxrat/build.apk"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/usr/share/apkmod, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see `proot --help`.

**Comment by Hax4us** [comment]
Install apkmod from here https://GitHub.com/Hax4Us/Apkmod

**Comment by Ondrik8** [comment]
`apt install openjdk-8-jre`

**Comment by nikolay06** [comment]
update-java-alternatives

**Comment by deadpool061** [comment]
It is showing request with option -a , plz help

**Comment by warlook69** [comment]
Se instala apkmod desde https://GitHub.com/Hax4Us/Apkmod y antes da más errores jajajaja

**Comment by qwertyuii786** [comment]
![Screenshot_2021-12-02-22-06-45-05](https://user-images.githubusercontent.com/95434440/144464136-82267016-444a-4da6-9c2c-74a6efe93ea4.jpg)
HaxRat fake tool it is not working....some peoples make money by making fake tools....views=money 🥺

**Comment by qwertyuii786** [comment]
![Screenshot_2021-12-02-22-06-45-05](https://user-images.githubusercontent.com/95434440/144464442-cd7a8f4e-9b56-4b7e-89ac-036ddbaca7d9.jpg)
Fake !! Don't try !! Don't waste your time guys...!!!!
