### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by H420Prajyot** [Hax4us/haxRat#5]
17/07/2020, 15:38:18 => ERROR | Build Failed - Build Command Failed - Command failed: apkmod -r "/home/kali/haxRat/server/app/factory/decompiled" -o "/data/data/com.termux/files/home/haxrat/build.apk" Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer; at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919) at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344) at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300) at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61) at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36) at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418) at brut.androlib.Androlib.buildSources(Androlib.java:349) at brut.androlib.Androlib.build(Androlib.java:301) at brut.androlib.Androlib.build(Androlib.java:268) at brut.apktool.Main.cmdBuild(Main.java:251) at brut.apktool.Main.main(Main.java:79)

**Comment by dev1434** [comment]
ERROR | Build Failed - Sign command Failed - Command failed: apksigner -p android keystore "/data/data/com.termux/files/home/haxrat/build.apk" "/data/data/com.termux/files/home/haxrat/haxRat.apk" Unsupported command: -p. See --help for supported commands

**Comment by Ondrik8** [comment]
`apt install openjdk-8-jre`

**Comment by azamet90** [comment]
> `apt install openjdk-8-jre`

this version of java is no more available on kali linux?
